//$(document).ready(function () {
//  $("#info").click(function () {
//   $('<p >').css('opacity', '1');
//    $("#searchdata").hide();
//    $(".reload").show();
//  });
//});
 
$(document).ready(function () {
  $("#info").click(function () {
    var p = $('<p id="prastavana">१. प्रस्तावना</p>');
    $("#div4").append(p);
    $("#info").hide();
    $("#prastavana").click(function () {
      $('#prastavana').load("display.html #prastavana");
$("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
$("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
$("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
$("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
$("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
$("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
$("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
$("#kanyadan").html('९. कन्यादान योजना');
$("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
$("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
$("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
$("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
$("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
$("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
$("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
$("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
$("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
$("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
$("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
$("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
$("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
$("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
$("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
$("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
$("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
$("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
$("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

    });
    var p = $('<p id="prakalpnihaygaonsankhya">२. प्रकल्प निहाय गाव संख्या</p>');
    $("#div4").append(p);
    $("#prakalpnihaygaonsankhya").click(function () {
            $('#prakalpnihaygaonsankhya').load("display.html #prakalpnihaygaonsankhya"); 
            $("#prastavana").html('१. प्रस्तावना');
            $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
            $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
            $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
            $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
            $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
            $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
            $("#kanyadan").html('९. कन्यादान योजना');
            $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
            $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
            $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
            $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
            $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
            $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
            $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
            $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
            $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
            $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
            $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
            $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
            $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
            $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
            $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
            $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
            $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
            $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
            $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');
    });
    var p = $('<p id="eklawya">३. एकलव्य-मॉडेल रेसिडन्सी स्कूल</p>');
    $("#div4").append(p);
    $("#eklawya").click(function () {
      $('#eklawya').load("display.html #eklawya");
            $("#prastavana").html('१. प्रस्तावना');
            $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
            $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
            $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
            $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
            $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
            $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
            $("#kanyadan").html('९. कन्यादान योजना');
            $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
            $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
            $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
            $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
            $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
            $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
            $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
            $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
            $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
            $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
            $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
            $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
            $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
            $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
            $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
            $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
            $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
            $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
            $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

    });

      var p = $('<p id="yashogathamissionpalodi">४. यशोगाथा मिशन पालोदी</p>');
      $("#div4").append(p);
      $("#yashogathamissionpalodi").click(function () {
        $('#yashogathamissionpalodi').load("display.html #yashogathamissionpalodi");
            $("#prastavana").html('१. प्रस्तावना');
            $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
            $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
            $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
            $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
            $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
            $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
            $("#kanyadan").html('९. कन्यादान योजना');
            $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
            $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
            $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
            $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
            $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
            $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
            $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
            $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
            $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
            $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
            $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
            $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
            $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
            $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
            $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
            $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
            $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
            $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
            $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

      });
      var p = $('<p id="suvarnmohtsavi">५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना</p>');
      $("#div4").append(p);
      $("#suvarnmohtsavi").click(function () {
        $('#suvarnmohtsavi').load("display.html #suvarnmohtsavi");
            $("#prastavana").html('१. प्रस्तावना');
            $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
            $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
            $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
            $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
            $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
            $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
            $("#kanyadan").html('९. कन्यादान योजना');
            $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
            $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
            $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
            $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
            $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
            $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
            $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
            $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
            $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
            $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
            $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
            $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
            $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
            $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
            $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
            $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
            $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
            $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
            $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

      });
      var p = $('<p id="shikshnikyojana">६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना</p>');
    $("#div4").append(p);
    $("#shikshnikyojana").click(function () {
      $('#shikshnikyojana').load("display.html #shikshnikyojana");
      $("#prastavana").html('१. प्रस्तावना');
      $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
      $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
      $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
      $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
      $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
      $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
      $("#kanyadan").html('९. कन्यादान योजना');
      $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
      $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
      $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
      $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
      $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
      $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
      $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
      $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
      $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
      $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
      $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
      $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
      $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
      $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
      $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
      $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
      $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
      $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
      $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');
      
    });
    var p = $('<p id="foreignscholarship">७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना</p>');
    $("#div4").append(p);
    $("#foreignscholarship").click(function () {
      $('#foreignscholarship').load("display.html #foreignscholarship");
      $("#prastavana").html('१. प्रस्तावना');
      $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
      $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
      $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
      $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
      $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
      $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
      $("#kanyadan").html('९. कन्यादान योजना');
      $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
      $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
      $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
      $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
      $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
      $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
      $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
      $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
      $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
      $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
      $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
      $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
      $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
      $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
      $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
      $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
      $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
      $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
      $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

    
    });
    var p = $('<p id="pdtdindayalupadyay">८. पंडीत दीनदयाल उपाध्याय स्वयं योजना</p>');
    $("#div4").append(p);
    $("#pdtdindayalupadyay").click(function () {
      $('#pdtdindayalupadyay').load("display.html #pdtdindayalupadyay"); 
      $("#prastavana").html('१. प्रस्तावना');
      $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
      $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
      $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
      $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
      $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
      $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
      $("#kanyadan").html('९. कन्यादान योजना');
      $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
      $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
      $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
      $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
      $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
      $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
      $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
      $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
      $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
      $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
      $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
      $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
      $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
      $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
      $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
      $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
      $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
      $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
      $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');
   
    });
    var p = $('<p id="kanyadan">९. कन्यादान योजना</p>');
    $("#div4").append(p);
    $("#kanyadan").click(function () {
      $('#kanyadan').load("display.html #kanyadan");
      $("#prastavana").html('१. प्रस्तावना');
      $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
      $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
      $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
      $("#prakalpnihaygaonsankhya").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
      $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
      $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
      $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
      $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
      $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
      $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
      $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
      $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
      $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
      $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
      $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
      $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
      $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
      $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
      $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
      $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
      $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
      $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
      $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
      $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
      $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
      $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');
    });
    var p = $('<p id="sanskrutiksabhagruh">१०. सांस्कृतिक सभागृह</p>');
    $("#div4").append(p);
    $("#sanskrutiksabhagruh").click(function () {
      $('#sanskrutiksabhagruh').load("display.html #sanskrutiksabhagruh");
      $("#prastavana").html('१. प्रस्तावना');
      $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
      $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
      $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
      $("#prakalpnihaygaonsankhya").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
      $("#prakalpnihaygaonsankhya").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
      $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
      $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
      $("#kanyadan").html('९. कन्यादान योजना');
      $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
      $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
      $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
      $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
      $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
      $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
      $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
      $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
      $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
      $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
      $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
      $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
      $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
      $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
      $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
      $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
      $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
      $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

    });
    var p = $('<p id="nagarisevaspardhapariksha">११. नागरी सेवा स्पर्धा परीक्षा</p>');
    $("#div4").append(p);
    $("#nagarisevaspardhapariksha").click(function () {
    $('#nagarisevaspardhapariksha').load("display.html #nagarisevaspardhapariksha");
    $("#prastavana").html('१. प्रस्तावना');
    $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
    $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
    $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
    $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
    $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
    $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
    $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
    $("#kanyadan").html('९. कन्यादान योजना');
    $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
    $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
    $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
    $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
    $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
    $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
    $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
    $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
    $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
    $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
    $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
    $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
    $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
    $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
    $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
    $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
    $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
    $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

   });
   var p = $('<p id="bharatsarkarpostmatric">१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती</p>');
   $("#div4").append(p);
   $("#bharatsarkarpostmatric").click(function () {
     $('#bharatsarkarpostmatric').load("display.html #bharatsarkarpostmatric");
     $("#prastavana").html('१. प्रस्तावना');
    $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
    $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
    $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
    $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
    $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
    $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
    $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
    $("#kanyadan").html('९. कन्यादान योजना');
    $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
    $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
    $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
    $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
    $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
    $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
    $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
    $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
    $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
    $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
    $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
    $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
    $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
    $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
    $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
    $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
    $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
    $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

   });
   var p = $('<p id="drapjabdulkalamamrutahar">१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना</p>');
   $("#div4").append(p);
  $("#drapjabdulkalamamrutahar").click(function () {
    $('#drapjabdulkalamamrutahar').load("display.html #drapjabdulkalamamrutahar");
    $("#prastavana").html('१. प्रस्तावना');
    $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
    $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
    $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
    $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
    $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
    $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
    $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
    $("#kanyadan").html('९. कन्यादान योजना');
    $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
    $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
    $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
    $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
    $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
    $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
    $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
    $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
    $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
    $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
    $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
    $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
    $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
    $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
    $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
    $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
    $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
    $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');
  });
  var p = $('<p id="pradhanmantrivandanvikas">१४. प्रधानमंत्री वंदन विकास योजना</p>');
  $("#div4").append(p);
  $("#pradhanmantrivandanvikas").click(function () {
   $('#pradhanmantrivandanvikas').load("display.html #pradhanmantrivandanvikas");
    $("#prastavana").html('१. प्रस्तावना');
    $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
    $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
    $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
    $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
    $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
    $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
    $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
    $("#kanyadan").html('९. कन्यादान योजना');
    $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
    $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
    $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
    $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
    $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
    $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
    $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
    $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
    $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
    $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
    $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
    $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
    $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
    $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
    $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
    $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
    $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
    $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

 });
    var p = $('<p id="shabariadiwasigharkul">१५. शबरी आदिवासी घरकुल</p>');
      $("#div4").append(p);
      $("#shabariadiwasigharkul").click(function () {
      $('#shabariadiwasigharkul').load("display.html #shabariadiwasigharkul");
      $("#prastavana").html('१. प्रस्तावना');
      $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
      $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
      $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
      $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
      $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
      $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
      $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
      $("#kanyadan").html('९. कन्यादान योजना');
      $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
      $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
      $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
      $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
      $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
      $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
      $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
      $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
      $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
      $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
      $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
      $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
      $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
      $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
      $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
      $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
      $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
      $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');


    });
    var p = $('<p id="nucleusbajetheading">१६. प्नुक्लिअस बजेट</p>');
    $("#div4").append(p);
   $("#nucleusbajetheading").click(function () {
     $('#nucleusbajetheading').load("display.html #nucleusbajetheading");
      $("#prastavana").html('१. प्रस्तावना');
      $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
      $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
      $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
      $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
      $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
      $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
      $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
      $("#kanyadan").html('९. कन्यादान योजना');
      $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
      $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
      $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
      $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
      $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
      $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
      $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
      $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
      $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
      $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
      $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
      $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
      $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
      $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
      $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
      $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
      $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
      $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

   });
   var p = $('<p id="shetkariutpadaksanstha">१७. शेतकरी उत्पादक संस्था</p>');
   $("#div4").append(p);
  $("#shetkariutpadaksanstha").click(function () {
    $('#shetkariutpadaksanstha').load("display.html #shetkariutpadaksanstha");
    $("#prastavana").html('१. प्रस्तावना');
    $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
    $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
    $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
    $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
    $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
    $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
    $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
    $("#kanyadan").html('९. कन्यादान योजना');
    $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
    $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
    $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
    $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
    $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
    $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
    $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
    $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
    $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
    $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
    $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
    $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
    $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
    $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
    $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
    $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
    $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
    $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

  });
  
  var p = $('<p id="jilhawarshikadiwasi">१८. जिल्हा वार्षिक आदिवासी उपाय योजना</p>');
  $("#div4").append(p);
  $("#jilhawarshikadiwasi").click(function () {
   $('#jilhawarshikadiwasi').load("display.html #jilhawarshikadiwasi");
     $("#prastavana").html('१. प्रस्तावना');
    $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
    $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
    $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
    $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
    $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
    $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
    $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
    $("#kanyadan").html('९. कन्यादान योजना');
    $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
    $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
    $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
    $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
    $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
    $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
    $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
    $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
    $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
    $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
    $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
    $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
    $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
    $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
    $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
    $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
    $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
    $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');


 });
 var p = $('<p id="wanhakkakayda२00६">१९. वन हक्क कायदा २००६</p>');
 $("#div4").append(p);
$("#wanhakkakayda२00६").click(function () {
  $('#div4').load("display.html #wanhakkakayda२00६");
  $("#prastavana").html('१. प्रस्तावना');
  $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
  $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
  $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
  $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
  $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
  $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
  $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
  $("#kanyadan").html('९. कन्यादान योजना');
  $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
  $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
  $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
  $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
  $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
  $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
  $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
  $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
  $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
  $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
  $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
  $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
  $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
  $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
  $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
  $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
  $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
  $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

});
var p = $('<p id="krantikarakbirsamunda">२०. क्रानतिकारी बिर्रसामुंडा</p>');
$("#div4").append(p);
$("#krantikarakbirsamunda").click(function () {
 $('#krantikarakbirsamunda').load("display.html #krantikarakbirsamunda");
  $("#prastavana").html('१. प्रस्तावना');
  $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
  $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
  $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
  $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
  $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
  $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
  $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
  $("#kanyadan").html('९. कन्यादान योजना');
  $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
  $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
  $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
  $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
  $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
  $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
  $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
  $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
  $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
  $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
  $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
  $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
  $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
  $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
  $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
  $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
  $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
  $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

});
var p = $('<p id="thakkarbaba">२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना</p>');
$("#div4").append(p);
$("#thakkarbaba").click(function () {
$('#thakkarbaba').load("display.html #thakkarbaba");
    $("#prastavana").html('१. प्रस्तावना');
    $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
    $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
    $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
    $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
    $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
    $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
    $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
    $("#kanyadan").html('९. कन्यादान योजना');
    $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
    $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
    $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
    $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
    $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
    $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
    $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
    $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
    $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
    $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
    $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
    $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
    $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
    $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
    $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
    $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
    $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

});
var p = $('<p id="bhumihin">२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना</p>');
$("#div4").append(p);
$("#bhumihin").click(function () {
 $('#bhumihin').load("display.html #bhumihin");
  $("#prastavana").html('१. प्रस्तावना');
  $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
  $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
  $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
  $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
  $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
  $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
  $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
  $("#kanyadan").html('९. कन्यादान योजना');
  $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
  $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
  $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
  $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
  $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
  $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
  $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
  $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
  $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
  $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
  $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
  $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');

  $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
  $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
  $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
  $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
  $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
  $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

});
var p = $('<p id="pardhiyojana">२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना</p>');
$("#div4").append(p);
$("#pardhiyojana").click(function () {
 $('#pardhiyojana').load("display.html #pardhiyojana");
  $("#prastavana").html('१. प्रस्तावना');
  $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
  $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
  $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
  $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
  $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
  $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
  $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
  $("#kanyadan").html('९. कन्यादान योजना');
  $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
  $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
  $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
  $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
  $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
  $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
  $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
  $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
  $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
  $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
  $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
  $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
  $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');

  $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
  $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
  $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
  $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
  $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

});
var p = $('<p id="nucleusbagetheading">२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट</p>');
$("#div4").append(p);
$("#nucleusbagetheading").click(function () {
 $('#nucleusbagetheading').load("display.html #nucleusbagetheading");
  $("#prastavana").html('१. प्रस्तावना');
  $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
  $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
  $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
  $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
  $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
  $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
  $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
  $("#kanyadan").html('९. कन्यादान योजना');
  $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
  $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
  $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
  $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
  $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
  $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
  $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
  $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
  $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
  $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
  $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
  $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
  $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
  $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');

  $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
  $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
  $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
  $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

});
var p = $('<p id="kaushalyakaryakram">२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम</p>');
$("#div4").append(p);
$("#kaushalyakaryakram").click(function () {
 $('#kaushalyakaryakram').load("display.html #kaushalyakaryakram");
  $("#prastavana").html('१. प्रस्तावना');
  $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
  $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
  $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
  $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
  $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
  $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
  $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
  $("#kanyadan").html('९. कन्यादान योजना');
  $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
  $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
  $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
  $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
  $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
  $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
  $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
  $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
  $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
  $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
  $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
  $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
  $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
  $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
  $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');

  $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
  $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
  $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

});
var p = $('<p id="manavsansadhan">२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना</p>');
$("#div4").append(p);
$("#manavsansadhan").click(function () {
 $('#manavsansadhan').load("display.html #manavsansadhan");
    $("#prastavana").html('१. प्रस्तावना');
    $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
    $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
    $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
    $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
                $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
    $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
    $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
    $("#kanyadan").html('९. कन्यादान योजना');
    $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
    $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
    $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
    $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
    $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
    $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
    $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
    $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
    $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
    $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
    $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
    $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
    $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
    $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
    $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
    $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');

    $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');
    $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

});
var p = $('<p id="shaskiyawastigruh">२७. शासकीय वसतिगृह</p>');
$("#div4").append(p);
$("#shaskiyawastigruh").click(function () {
 $('#shaskiyawastigruh').load("display.html #shaskiyawastigruh");
  $("#prastavana").html('१. प्रस्तावना');
  $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
  $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
  $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
  $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
  $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
  $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
  $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
  $("#kanyadan").html('९. कन्यादान योजना');
  $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
  $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
  $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
  $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
  $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
  $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
  $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
  $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
  $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
  $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
  $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
  $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
  $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
  $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
  $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
  $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
  $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');

  $("#shaskiyashramshala").html('२८. शासकीय आश्रम शाळा');

});
var p = $('<p id="shaskiyashramshala">२८. शासकीय आश्रम शाळा</p>');
$("#div4").append(p);
$("#shaskiyashramshala").click(function () {
 $('#shaskiyashramshala').load("display.html #shaskiyashramshala");
  $("#prastavana").html('१. प्रस्तावना');
  $("#prakalpnihaygaonsankhya").html('२. प्रकल्प निहाय गाव संख्या');
  $("#eklawya").html('३. एकलव्य-मॉडेल रेसिडन्सी स्कूल');
  $("#yashogathamissionpalodi").html('४. यशोगाथा मिशन पालोदी');
  $("#suvarnmohtsavi").html('५. सुवर्ण मोहत्सवी पूर्व माद्यमिक शिष्यवृत्ती योजना');
  $("#shikshnikyojana").html('६. आदिवासी सशोधन व प्रशिक्षण संस्था, पुणे विविध प्रशिक्षण योजना');
  $("#foreignscholarship").html('७. आदिवासी जमातीच्या मुलामुलींना परदेशात शिक्षणासाठी शिष्यवृत्ती योजना');
  $("#pdtdindayalupadyay").html('८. पंडीत दीनदयाल उपाध्याय स्वयं योजना');
  $("#kanyadan").html('९. कन्यादान योजना');
  $("#sanskrutiksabhagruh").html('१०. सांस्कृतिक सभागृह');
  $("#nagarisevaspardhapariksha").html('११. नागरी सेवा स्पर्धा परीक्षा');
  $("#bharatsarkarpostmatric").html('१२. भारत सरकार पोस्ट मेट्रिक शिष्यवृत्ती');
  $("#drapjabdulkalamamrutahar").html('१३. डॉक्टर एपीजे अब्दुल कलाम अमृत आहार योजना');
  $("#pradhanmantrivandanvikas").html('१४. प्रधानमंत्री वंदन विकास योजना');
  $("#shabariadiwasigharkul").html('१५. शबरी आदिवासी घरकुल');
  $("#nucleusbajetheading").html('१६. प्नुक्लिअस बजेट');
  $("#shetkariutpadaksanstha").html('१७. शेतकरी उत्पादक संस्था');
  $("#jilhawarshikadiwasi").html('१८. जिल्हा वार्षिक आदिवासी उपाय योजना');
  $("#wanhakkakayda2006").html('१९. वन हक्क कायदा २००६');
  $("#krantikarakbirsamunda").html('२०. क्रानतिकारी बिर्रसामुंडा');
  $("#thakkarbaba").html('२१. ठक्कर बाबा आदिवासी वस्ती सुधारणा योजना');
  $("#pardhiyojana").html('२२. भूमिहीन दारिद्र्य रेषे खालील आदिवासींचे सबलीकरण व स्वाभिमान योजना');
  $("#pardhiyojana").html('२३. जिल्हा वार्षिक आदिवासी उपयोजने अंतर्गत पारधी विकास योजना');
  $("#nucleusbagetheading").html('२४. केंद्रवर्ती अर्थसंकल्प योजना - न्युक्लिअस बजेट');
  $("#kaushalyakaryakram").html('२५. प्रशिक्षण योजना / कौशल्य विकास कार्यक्रम');
  $("#manavsansadhan").html('२६. मानव साधन संपत्ती विकासाच्या व आदिवासी क्ल्यानात्मक योजना');
  $("#shaskiyawastigruh").html('२७. शासकीय वसतिगृह');


     });

});
  });



$(document).ready(function () {

  $("#prastavsthiti").click(function () {

    var p = $('<span id="prastavsthiti">"खालील रिक्त जागेवर लाभार्थीचे नाव व आडनाव टाईप करून press बटन दाबा"</span>');
    p.attr("id", "prastavsthiti");
    $("#div4").append(p);
    $("#searchdata").show();
    $("#prastavsthiti").hide();
    $("#info").hide();
    $("#prastavana").hide();
    $("#prakalpnihaygaonsankhya").hide();
    $("#eklawya").hide();
    $("#yashogathamissionpalodi").hide();
    $("#suvarnmohtsavi").hide();
    $("#shikshnikyojana").hide();
    $("#foreignscholarship").hide();
    $("#pdtdindayalupadyay").hide();
    $("#kanyadan").hide();
    $("#sanskrutiksabhagruh").hide();
    $("#nagarisevaspardhapariksha").hide();
    $("#bharatsarkarpostmatric").hide();
    $("#drapjabdulkalamamrutahar").hide();
    $("#pradhanmantrivandanvikas").hide();
    $("#shabariadiwasigharkul").hide();
    $("#nucleusbajetheading").hide();
    $("#wanhakkakayda२00६").hide();
    $("#shetkariutpadaksanstha").hide();
    $("#jilhawarshikadiwasi").hide();
    $("#wanhakkakayda2006").hide();
    $("#krantikarakbirsamunda").hide();
    $("#thakkarbaba").hide();
    $("#bhumihin").hide();
    $("#pardhiyojana").hide();
    $("#nucleusbagetheading").hide();
    $("#kaushalyakaryakram").hide();
    $("#manavsansadhan").hide();
    $("#shaskiyawastigruh").hide();
    $("#shaskiyashramshala").hide();

  });
});

// $(document).ready(function () {
//   $('#intro').on('animationend', function () {
//     // Animation has ended, update opacity to 1
//     $(this).css('opacity', '1');
//   });
//   $('#info').on('animationend', function () {
//     // Animation has ended, update opacity to 1
//     $(this).css('opacity', '1');
//   });
//   $('#prastavsthiti').on('animationend', function () {
//     // Animation has ended, update opacity to 1
//     $(this).css('opacity', '1');
//   });
//   $('#div4').on('animationend', function () {
//     // Animation has ended, update opacity to 1
//     $(this).css('opacity', '1');
//   });
//   $('.div1').on('animationend', function () {
//     // Animation has ended, update opacity to 1
//     $(p).css('opacity', '1');
//   });
// }); 
